" Basic Settings
set nocompatible
set encoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936
set termencoding=utf-8
set fileformats=unix

" UI Settings
set background=dark
set termguicolors
" Use gruvbox if available, otherwise default colorscheme
silent! colorscheme gruvbox
set number
set cursorline
set laststatus=2
set showmatch
set showcmd
set ruler

" Editor Settings
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent
set nowrap

" Search Settings
set hlsearch
set incsearch
set ignorecase
set smartcase

" Performance Settings
set lazyredraw
set ttyfast
set noundofile
set nobackup
set noswapfile

" File Type Settings
filetype plugin indent on
syntax enable

" Key Mappings
let mapleader = " "
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>e :Explore<CR>
nnoremap <leader>c :set cursorline!<CR>

" Auto Commands
if has("autocmd")
  augroup vimrc
    autocmd!
    " Remember last position
    autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
  augroup END
endif
